logging:
  level: INFO
  loggers:
    com.owainlewis: DEBUG

# Database settings.
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.cj.jdbc.Driver
  # the username
  user: admin
  # the password
  password: password
  # the JDBC URL; the database is called hello_world
  url: jdbc:mysql://localhost:3306/employees
  # the SQL query to run when validating a connection's liveness
  validationQuery: "SELECT 1"
